name: Build MATLAB docs

on:
  push:
    branches: [ main ]   # o la rama que uses

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run build_docs.m
        uses: matlab-actions/run-command@v2
        with:
          command: build_docs